/* brage_bdcut58.baf
Brage was left standing in bd4700.are - make sure he's coming to the last hell area, too */

IF
  Global("C#Brage_kicked_bd4700","global",1) //set in C#BrageP.dlg
  !Dead("C#Brage")
  !InParty("C#Brage")
THEN
  RESPONSE #100
    CutSceneId(Player1)
    MoveGlobal("bd4400","C#Brage",[1103.1276]) //coordinates somewhere near the portal in bd4400.are. 
    ActionOverride("C#Brage",Face(E))     
END